### ISSUE TITLE
[1.14.4] Seems to disable yellow splash txt?

### ISSUE THREAD

**Issue by fuzzyweapon** [GirafiStudios/BetterTitleScreen#11]
MC: 1.14.4
Forge: 28.1.61
BTS: 1.7

----

splash.txt inside the minecraft jar (or from a resourcepack) contains options for the yellow splash text.

This mod seems to be unobtrusive to the user for the most part (it only modifies things that it allows for modification).  It'd be nice if this was still supported.

I have not tested overriding splash.txt from a resourcepack so I can't answer to whether that functionality is still available.

**Comment by GirafiStudios** [comment]
Thanks for your report!
Better Title Screen does not touch anything related to the splash text at all. Most likely caused by another mod you're using.
Screenshot using the exact versions you mentioned:
![7vgTk6a](https://user-images.githubusercontent.com/6305377/69014445-b54bc500-098a-11ea-9a7a-55f956c2f076.png)
